language: java
jdk:
- oraclejdk8

sudo: false

before_install:
- apt-get install sharutils

after_failure:
- tar cjf - $(find . -type d -name 'failsafe-reports' -o -name 'surefire-reports') | uuencode reports.tar.bz2
